# Generated by Django 2.1.3 on 2018-11-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_classe', models.CharField(max_length=5)),
                ('libelle_classe', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse_rue', models.CharField(max_length=30, unique=True)),
                ('adresse_ville', models.CharField(max_length=30, unique=True)),
                ('adresse_postale', models.CharField(max_length=30, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('date_creation', models.DateField()),
                ('statut', models.CharField(max_length=30, unique=True)),
                ('categorie', models.CharField(max_length=30, unique=True)),
                ('niveau', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_scolarite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='classes',
            field=models.ManyToManyField(through='visibility.EtablissementClasse', to='visibility.Classe'),
        ),
    ]
