# Generated by Django 2.1.3 on 2018-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='categorie',
            field=models.CharField(choices=[('Laic', 'Laic'), ('Catholique', 'Catholique'), ('Protestant', 'Protestant')], max_length=15),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='niveau',
            field=models.CharField(choices=[('EG', 'Enseignement Général'), ('L', 'Lycée'), ('U', 'Université')], max_length=5),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='statut',
            field=models.CharField(choices=[('Public', 'Public'), ('Privé', 'Privé')], max_length=10),
        ),
    ]
