# Generated by Django 2.1.3 on 2016-02-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0004_auto_20181107_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementClasseSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('etablissement_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.EtablissementClasse')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementClasseSpecialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_scolarite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.EtablissementClasse')),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementNiveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_niveau', models.CharField(max_length=5)),
                ('description_niveau', models.CharField(max_length=40)),
                ('type_niveau', models.CharField(choices=[('GEN', 'Général'), ('TECH', 'Technique')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_serie', models.CharField(max_length=5)),
                ('description_serie', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_specialite', models.CharField(max_length=5)),
                ('description_specialite', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='etablissement',
            old_name='categorie',
            new_name='ordre_enseignement',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='statut',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé'), ('COMMUNAUTAIRE', 'Communautaire')], max_length=10),
        ),
        migrations.AddField(
            model_name='etablissementniveau',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Etablissement'),
        ),
        migrations.AddField(
            model_name='etablissementniveau',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Niveau'),
        ),
        migrations.AddField(
            model_name='etablissementclassespecialite',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Specialite'),
        ),
        migrations.AddField(
            model_name='etablissementclasseserie',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visibility.Serie'),
        ),
        migrations.AddField(
            model_name='etablissementclasse',
            name='series',
            field=models.ManyToManyField(through='visibility.EtablissementClasseSerie', to='visibility.Serie'),
        ),
        migrations.AddField(
            model_name='etablissementclasse',
            name='specialites',
            field=models.ManyToManyField(through='visibility.EtablissementClasseSpecialite', to='visibility.Specialite'),
        ),
    ]
