# Generated by Django 2.1.3 on 2016-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0007_auto_20160211_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='type_niveau',
            field=models.CharField(choices=[('GEN', 'Général'), ('TECH', 'Technique'), (None, 'Sélectionnez un niveau')], max_length=15, null=True),
        ),
    ]
