# Generated by Django 2.1.3 on 2016-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0009_auto_20160211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='description_serie',
            field=models.CharField(max_length=30),
        ),
    ]
