# Generated by Django 2.1.3 on 2019-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visibility', '0011_auto_20160211_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'niveau', 'verbose_name_plural': 'niveaux'},
        ),
    ]
